language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.10"
install:
  - Xvfb -ac -screen scrn 1280x2000x24 :9.0 &
  - export DISPLAY=':9.0'
  - npm install electron-prebuilt
  - npm install
addons:
  apt:
    packages:
      - libgtk2.0-0
      - libgconf-2-4
      - libasound2
      - libxtst6
      - libxss1
      - libnss3
      - xvfb
