language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.10"
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install electron-prebuilt
  - npm install
addons:
  apt:
    packages:
      - libgtk2.0-0
      - libgconf-2-4
      - libasound2
      - libxtst6
      - libxss1
      - libnss3
      - xvfb
